"""Train and evaluate a lightweight StainPQR coverage utility selector.

Input is Stage 1B `actions.csv` generated by the coverage-action decoder oracle.
The script trains two small CPU-only heads:

  - logistic risk head: P(Delta PQ > 0)
  - ridge utility head: E[Delta PQ]

The main selector score is:

    expected_utility = P(Delta PQ > 0) * max(E[Delta PQ], 0)

The script compares this learned score against strong rule baselines such as
`decoded_iou_high`, `added_area`, and `missed_like_proxy` under small per-image
budgets.
"""

from __future__ import annotations

import argparse
import csv
import json
import math
from pathlib import Path

import numpy as np


FEATURE_NAMES = [
    "rank_norm",
    "evidence",
    "residual_evidence",
    "decoded_predicted_iou",
    "decoded_stability_score",
    "log_decoded_area",
    "log_added_area",
    "added_area_ratio",
    "area_minus_added_log",
]


def _to_float(value, default: float = math.nan) -> float:
    if value is None or value == "":
        return default
    try:
        return float(value)
    except ValueError:
        return default


def _to_int(value, default: int = 0) -> int:
    if value is None or value == "":
        return default
    try:
        return int(float(value))
    except ValueError:
        return default


def _load_actions(paths: list[Path]) -> list[dict]:
    rows: list[dict] = []
    for path in paths:
        with open(path, "r", encoding="utf-8-sig", newline="") as f:
            lines = [line for line in f if line.strip()]
            reader = csv.DictReader(lines)
            for row in reader:
                decoded_area = _to_float(row.get("decoded_area"), 0.0)
                added_area = _to_float(row.get("added_area"), 0.0)
                delta_pq = _to_float(row.get("delta_pq"), 0.0)
                item = {
                    "source_csv": str(path),
                    "image": str(row.get("image", "")),
                    "group": f"{path}::{row.get('image', '')}",
                    "target_error": str(row.get("target_error", "")),
                    "action_rank": _to_int(row.get("action_rank"), 0),
                    "evidence": _to_float(row.get("evidence"), 0.0),
                    "residual_evidence": _to_float(row.get("residual_evidence"), 0.0),
                    "decoded_predicted_iou": _to_float(row.get("decoded_predicted_iou"), 0.0),
                    "decoded_stability_score": _to_float(row.get("decoded_stability_score"), 0.0),
                    "decoded_area": decoded_area,
                    "added_area": added_area,
                    "delta_pq": delta_pq,
                    "delta_dq": _to_float(row.get("delta_dq"), 0.0),
                    "delta_sq": _to_float(row.get("delta_sq"), 0.0),
                    "delta_aji": _to_float(row.get("delta_aji"), 0.0),
                    "positive": bool(delta_pq > 0),
                    "harmful": bool(delta_pq < 0),
                }
                rows.append(item)
    return rows


def _feature_row(row: dict, max_rank: int = 19) -> list[float]:
    decoded_area = max(0.0, float(row["decoded_area"]))
    added_area = max(0.0, float(row["added_area"]))
    rank_norm = float(row["action_rank"]) / max(1.0, float(max_rank))
    return [
        rank_norm,
        float(row["evidence"]),
        float(row["residual_evidence"]),
        float(row["decoded_predicted_iou"]),
        float(row["decoded_stability_score"]),
        math.log1p(decoded_area),
        math.log1p(added_area),
        float(added_area / max(1.0, decoded_area)),
        math.log1p(max(0.0, decoded_area - added_area)),
    ]


def _matrix(rows: list[dict], mean=None, std=None):
    max_rank = 19
    x = np.asarray([_feature_row(row, max_rank=max_rank) for row in rows], dtype=np.float64)
    y_cls = np.asarray([1.0 if row["positive"] else 0.0 for row in rows], dtype=np.float64)
    y_reg = np.asarray([float(row["delta_pq"]) for row in rows], dtype=np.float64)
    if mean is None:
        mean = x.mean(axis=0)
    if std is None:
        std = x.std(axis=0)
        std[std < 1e-8] = 1.0
    x_std = (x - mean) / std
    x_aug = np.concatenate([np.ones((x.shape[0], 1), dtype=np.float64), x_std], axis=1)
    return x_aug, y_cls, y_reg, mean, std


def _sigmoid(z: np.ndarray) -> np.ndarray:
    return 1.0 / (1.0 + np.exp(-np.clip(z, -40.0, 40.0)))


def _train_logistic(
    x: np.ndarray,
    y: np.ndarray,
    *,
    lr: float,
    epochs: int,
    l2: float,
) -> np.ndarray:
    w = np.zeros(x.shape[1], dtype=np.float64)
    n_pos = max(1.0, float(y.sum()))
    n_neg = max(1.0, float((1.0 - y).sum()))
    weights = np.where(y > 0.5, len(y) / (2.0 * n_pos), len(y) / (2.0 * n_neg))
    for _ in range(int(epochs)):
        p = _sigmoid(x @ w)
        grad = x.T @ ((p - y) * weights) / len(y)
        grad[1:] += l2 * w[1:]
        w -= lr * grad
    return w


def _train_ridge(x: np.ndarray, y: np.ndarray, *, l2: float) -> np.ndarray:
    reg = np.eye(x.shape[1], dtype=np.float64) * float(l2)
    reg[0, 0] = 0.0
    return np.linalg.solve(x.T @ x + reg, x.T @ y)


def _safe_auc(labels: np.ndarray, scores: np.ndarray):
    labels = labels.astype(bool)
    finite = np.isfinite(scores)
    labels = labels[finite]
    scores = scores[finite]
    n_pos = int(labels.sum())
    n_neg = int((~labels).sum())
    if n_pos == 0 or n_neg == 0:
        return None
    order = np.argsort(scores)
    ranks = np.empty_like(order, dtype=np.float64)
    ranks[order] = np.arange(1, len(scores) + 1)
    unique_scores, inverse = np.unique(scores, return_inverse=True)
    for idx in range(len(unique_scores)):
        mask = inverse == idx
        if int(mask.sum()) > 1:
            ranks[mask] = float(ranks[mask].mean())
    rank_sum_pos = float(ranks[labels].sum())
    auc = (rank_sum_pos - n_pos * (n_pos + 1) / 2.0) / (n_pos * n_neg)
    return float(auc)


def _safe_ap(labels: np.ndarray, scores: np.ndarray):
    labels = labels.astype(bool)
    finite = np.isfinite(scores)
    labels = labels[finite]
    scores = scores[finite]
    n_pos = int(labels.sum())
    if n_pos == 0:
        return None
    order = np.argsort(-scores)
    sorted_labels = labels[order]
    tp = np.cumsum(sorted_labels)
    precision = tp / (np.arange(len(labels)) + 1)
    return float((precision * sorted_labels).sum() / n_pos)


def _brier(labels: np.ndarray, prob: np.ndarray):
    finite = np.isfinite(prob)
    if int(finite.sum()) == 0:
        return None
    return float(np.mean((prob[finite] - labels[finite]) ** 2))


def _ece(labels: np.ndarray, prob: np.ndarray, bins: int = 10):
    finite = np.isfinite(prob)
    labels = labels[finite]
    prob = prob[finite]
    if len(prob) == 0:
        return None
    total = len(prob)
    ece = 0.0
    for i in range(bins):
        lo = i / bins
        hi = (i + 1) / bins
        if i == bins - 1:
            mask = (prob >= lo) & (prob <= hi)
        else:
            mask = (prob >= lo) & (prob < hi)
        if int(mask.sum()) == 0:
            continue
        acc = float(labels[mask].mean())
        conf = float(prob[mask].mean())
        ece += float(mask.sum()) / total * abs(acc - conf)
    return float(ece)


def _baseline_score(row: dict, method: str) -> float:
    if method == "decoded_iou_high":
        return float(row["decoded_predicted_iou"])
    if method == "added_area":
        return float(row["added_area"])
    if method == "residual_evidence":
        return float(row["residual_evidence"])
    if method == "rank_first":
        return -float(row["action_rank"])
    if method == "missed_like_proxy":
        return (
            float(row["residual_evidence"])
            + 0.25 * float(row["decoded_predicted_iou"])
            + 0.25 * float(row["decoded_stability_score"])
            + 0.0005 * float(row["added_area"])
        )
    if method == "oracle_delta":
        return float(row["delta_pq"])
    raise ValueError(f"Unknown baseline method: {method}")


def _attach_scores(rows: list[dict], x: np.ndarray, w_cls: np.ndarray, w_reg: np.ndarray) -> list[dict]:
    prob = _sigmoid(x @ w_cls)
    pred_delta = x @ w_reg
    out = []
    for row, p, d in zip(rows, prob, pred_delta):
        item = dict(row)
        item["selector_prob"] = float(p)
        item["selector_delta"] = float(d)
        item["selector_expected_utility"] = float(p * max(0.0, d))
        out.append(item)
    return out


def _groups(rows: list[dict]) -> dict[str, list[dict]]:
    grouped: dict[str, list[dict]] = {}
    for row in rows:
        grouped.setdefault(str(row["group"]), []).append(row)
    return grouped


def _score(row: dict, method: str) -> float:
    if method in ("selector_prob", "selector_delta", "selector_expected_utility"):
        return float(row[method])
    return _baseline_score(row, method)


def _budget_metrics(rows: list[dict], methods: list[str], budgets: list[int]) -> dict:
    grouped = _groups(rows)
    total_positive = sum(1 for row in rows if row["positive"])
    out: dict[str, dict] = {}
    for method in methods:
        out[method] = {}
        for budget in budgets:
            chosen = []
            image_delta_sums = []
            for items in grouped.values():
                ordered = sorted(items, key=lambda row: _score(row, method), reverse=True)
                selected = ordered[:budget]
                chosen.extend(selected)
                image_delta_sums.append(float(sum(row["delta_pq"] for row in selected)))
            hits = sum(1 for row in chosen if row["positive"])
            harmful = sum(1 for row in chosen if row["harmful"])
            delta_sum = float(sum(row["delta_pq"] for row in chosen))
            out[method][str(budget)] = {
                "chosen": int(len(chosen)),
                "hits": int(hits),
                "harmful": int(harmful),
                "precision": float(hits / max(1, len(chosen))),
                "positive_recall": float(hits / max(1, total_positive)),
                "delta_pq_sum": delta_sum,
                "positive_delta_pq_sum": float(sum(max(0.0, row["delta_pq"]) for row in chosen)),
                "harmful_delta_pq_sum": float(sum(min(0.0, row["delta_pq"]) for row in chosen)),
                "mean_selected_delta_pq": float(delta_sum / max(1, len(chosen))),
                "images_improved_individual_sum": int(sum(1 for value in image_delta_sums if value > 0)),
            }
    return out


def _score_metrics(rows: list[dict], methods: list[str]) -> dict:
    labels = np.asarray([1.0 if row["positive"] else 0.0 for row in rows], dtype=np.float64)
    out = {}
    for method in methods:
        scores = np.asarray([_score(row, method) for row in rows], dtype=np.float64)
        item = {
            "auroc": _safe_auc(labels, scores),
            "ap": _safe_ap(labels, scores),
        }
        if method == "selector_prob":
            item["brier"] = _brier(labels, scores)
            item["ece"] = _ece(labels, scores)
        out[method] = item
    return out


def _split_group_folds(rows: list[dict], folds: int) -> list[tuple[list[dict], list[dict]]]:
    group_keys = sorted(_groups(rows).keys())
    out = []
    folds = max(2, int(folds))
    for fold in range(folds):
        test_keys = {key for idx, key in enumerate(group_keys) if idx % folds == fold}
        train_rows = [row for row in rows if row["group"] not in test_keys]
        test_rows = [row for row in rows if row["group"] in test_keys]
        out.append((train_rows, test_rows))
    return out


def _fit_predict(train_rows: list[dict], test_rows: list[dict], args) -> tuple[list[dict], dict]:
    x_train, y_train, y_reg, mean, std = _matrix(train_rows)
    x_test, _, _, _, _ = _matrix(test_rows, mean=mean, std=std)
    w_cls = _train_logistic(
        x_train,
        y_train,
        lr=float(args.lr),
        epochs=int(args.epochs),
        l2=float(args.l2_cls),
    )
    w_reg = _train_ridge(x_train, y_reg, l2=float(args.l2_reg))
    pred_rows = _attach_scores(test_rows, x_test, w_cls, w_reg)
    model = {
        "feature_names": FEATURE_NAMES,
        "mean": mean.tolist(),
        "std": std.tolist(),
        "logistic_weights": w_cls.tolist(),
        "ridge_weights": w_reg.tolist(),
    }
    return pred_rows, model


def _write_predictions(path: Path, rows: list[dict]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fields = [
        "source_csv",
        "image",
        "action_rank",
        "target_error",
        "evidence",
        "residual_evidence",
        "decoded_predicted_iou",
        "decoded_stability_score",
        "decoded_area",
        "added_area",
        "delta_pq",
        "positive",
        "harmful",
        "selector_prob",
        "selector_delta",
        "selector_expected_utility",
    ]
    with open(path, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fields)
        writer.writeheader()
        for row in rows:
            writer.writerow({field: row.get(field, "") for field in fields})


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--train_actions", nargs="+", required=True, type=Path)
    parser.add_argument("--test_actions", nargs="+", default=None, type=Path)
    parser.add_argument("--out_dir", required=True, type=Path)
    parser.add_argument("--cv_folds", default=5, type=int)
    parser.add_argument("--budgets", nargs="+", default=[1, 2, 4, 8], type=int)
    parser.add_argument("--epochs", default=2500, type=int)
    parser.add_argument("--lr", default=0.05, type=float)
    parser.add_argument("--l2_cls", default=1e-3, type=float)
    parser.add_argument("--l2_reg", default=1e-2, type=float)
    args = parser.parse_args()

    train_rows = _load_actions(args.train_actions)
    if not train_rows:
        raise ValueError("No training actions loaded")

    args.out_dir.mkdir(parents=True, exist_ok=True)
    if args.test_actions:
        test_rows = _load_actions(args.test_actions)
        pred_rows, model = _fit_predict(train_rows, test_rows, args)
        mode = "holdout"
    else:
        pred_rows = []
        model = None
        for fold, (fold_train, fold_test) in enumerate(_split_group_folds(train_rows, args.cv_folds)):
            fold_pred, _ = _fit_predict(fold_train, fold_test, args)
            for row in fold_pred:
                row["cv_fold"] = fold
            pred_rows.extend(fold_pred)
        mode = "group_cv"
        # Also fit a final model on all rows for deployment/debugging.
        _, model = _fit_predict(train_rows, train_rows, args)

    methods = [
        "selector_expected_utility",
        "selector_prob",
        "selector_delta",
        "missed_like_proxy",
        "decoded_iou_high",
        "added_area",
        "residual_evidence",
        "rank_first",
        "oracle_delta",
    ]
    summary = {
        "mode": mode,
        "train_actions": [str(path) for path in args.train_actions],
        "test_actions": [str(path) for path in args.test_actions] if args.test_actions else None,
        "num_train_rows": len(train_rows),
        "num_eval_rows": len(pred_rows),
        "positive_rate_eval": float(sum(1 for row in pred_rows if row["positive"]) / max(1, len(pred_rows))),
        "score_metrics": _score_metrics(pred_rows, methods),
        "budget_metrics": _budget_metrics(pred_rows, methods, args.budgets),
    }

    with open(args.out_dir / "summary.json", "w", encoding="utf-8") as f:
        json.dump(summary, f, indent=2)
    with open(args.out_dir / "selector_model.json", "w", encoding="utf-8") as f:
        json.dump(model, f, indent=2)
    _write_predictions(args.out_dir / "predictions.csv", pred_rows)

    print(json.dumps(summary, indent=2))
    print(f"Wrote summary: {args.out_dir / 'summary.json'}")
    print(f"Wrote model: {args.out_dir / 'selector_model.json'}")
    print(f"Wrote predictions: {args.out_dir / 'predictions.csv'}")


if __name__ == "__main__":
    main()
